"use strict";

const PanelMcy = {
  _running: false,
  _logEl: null,
  _cmdEl: null,

  init() {
    this._logEl = document.getElementById("mcy-log");
    this._cmdEl = document.getElementById("mcy-cmd-preview");
    document.getElementById("btn-mcy-run").addEventListener("click", () => this.run());
    document.getElementById("btn-mcy-cancel").addEventListener("click", () => this.cancel());
    document.getElementById("btn-mcy-clear").addEventListener("click", () => this.refresh());
    document.getElementById("btn-mcy-browse").addEventListener("click", () => this._browse());
    document.getElementById("btn-mcy-gen").addEventListener("click", () => this._generate());
    document.getElementById("mcy-size").addEventListener("input", () => this._saveOptions());
    document.getElementById("mcy-opt-keep").addEventListener("change", () => this._saveOptions());
  },

  refresh() {
    this._loadOptions();
    const file = this._configFile();
    this._cmdEl.textContent = `mcy ${file || "mcy/top.cfg"}`;
    this._render("ready", "可以运行突变覆盖", [
      { state: file ? "success" : "pending", text: file ? `配置文件：${file}` : "请选择或生成 MCY 配置文件" },
      { state: "pending", text: "MCY 会评估测试对设计突变的覆盖能力" },
    ]);
    ToolStepUI.setTechnical("mcy", { meta: "等待运行 MCY", command: this._cmdEl.textContent, log: this._logEl.textContent });
  },

  async _browse() {
    const result = await window.vflux.openFileDialog({ title: "选择 MCY 配置文件", filters: [{ name: "MCY Config", extensions: ["cfg"] }, { name: "All Files", extensions: ["*"] }] });
    if (result?.filePaths?.[0]) {
      document.getElementById("mcy-config").value = result.filePaths[0];
      this.refresh();
    }
  },

  async _generate() {
    const proj = Config.data.project;
    const top = proj.top_module || "top";
    const path = `${Config.getProjectDir()}/mcy/${top}.cfg`;
    const size = document.getElementById("mcy-size").value || "10";
    const content = `# Auto-generated by Vflux\n[options]\nsize ${size}\n\n[script]\nread_verilog ${(proj.sources || []).join(" ")}\nprep -top ${top}\n`;
    await window.vflux.writeText(path, content);
    document.getElementById("mcy-config").value = path;
    App.setStatus("已生成 MCY 配置模板");
    this.refresh();
  },

  async run() {
    if (this._running) return;
    const file = this._configFile();
    if (!file) {
      this._render("failed", "还不能运行 MCY", [{ state: "failed", text: "请先选择或生成 MCY 配置文件" }]);
      return;
    }
    this._running = true;
    this._logEl.textContent = "";
    Pipeline.set("mcy", "running");
    App.setStatus("突变覆盖分析中...");
    this._render("running", "正在分析突变覆盖", [
      { state: "running", text: "读取 MCY 配置" },
      { state: "running", text: "生成并评估设计突变" },
    ]);
    const command = `mcy ${file}`;
    ToolStepUI.setTechnical("mcy", { meta: "运行中", command, log: "" });
    const result = await App.runTool("mcy", "mcy.exe", [file], Config.getProjectDir(), (t) => this._appendLog(t));
    this._running = false;
    ToolStepUI.setTechnical("mcy", { meta: `退出码：${result.code ?? 0}`, command, log: this._logEl.textContent });
    Pipeline.set("mcy", result.success ? "success" : "failed", result.success ? "" : `code:${result.code}`);
    this._render(result.success ? "success" : "failed", result.success ? "突变覆盖分析完成" : "突变覆盖分析失败", result.success ? [
      { state: "success", text: "MCY 已完成本次覆盖分析" },
    ] : ToolDiagnostics.analyze("mcy", this._logEl.textContent));
    App.setStatus(result.success ? "突变覆盖分析完成" : "突变覆盖分析失败");
    if (PanelDashboard) PanelDashboard.refresh();
  },

  cancel() {
    if (!this._running) return;
    App.cancelTool("mcy");
    this._running = false;
    Pipeline.set("mcy", "failed", "已取消");
    this._render("failed", "MCY 已取消", [{ state: "failed", text: "突变覆盖任务被中断" }]);
  },

  _configFile() { return document.getElementById("mcy-config").value.trim(); },
  _appendLog(text) { ToolStepUI.appendHiddenLog(this._logEl, text); },
  _render(kind, summary, items) { ToolStepUI.render("mcy-result", "mcy-summary", "mcy-feedback-list", kind, summary, items); },
  _saveOptions() {
    Config.setFlowValue("mcy", "size", Number(document.getElementById("mcy-size").value) || 10);
    Config.setFlowValue("mcy", "keep", !!document.getElementById("mcy-opt-keep").checked);
    this.refresh();
  },
  _loadOptions() {
    const flow = Config.getFlow("mcy");
    document.getElementById("mcy-size").value = flow.size || 10;
    document.getElementById("mcy-opt-keep").checked = flow.keep !== false;
  },
};
