"use strict";

const PanelVerilator = {
  _running: false,
  _logEl: null,
  _cmdEl: null,

  init() {
    this._logEl = document.getElementById("verilator-log");
    this._cmdEl = document.getElementById("verilator-cmd-preview");
    document.getElementById("verilator-mode").addEventListener("change", () => this.refresh());
    document.getElementById("btn-verilator-run").addEventListener("click", () => this.run());
    document.getElementById("btn-verilator-cancel").addEventListener("click", () => this.cancel());
    document.getElementById("btn-verilator-clear").addEventListener("click", () => this.refresh());
    document.getElementById("btn-verilator-browse").addEventListener("click", () => this._browseTb());
    document.getElementById("btn-verilator-gen-tb").addEventListener("click", () => this._generateTb());
    ["verilator-opt-wall", "verilator-opt-trace", "verilator-opt-coverage"].forEach((id) => {
      document.getElementById(id)?.addEventListener("change", () => this._saveOptions());
    });
  },

  refresh() {
    this._loadOptions();
    const command = this._buildCommand();
    this._cmdEl.textContent = command.text;
    const sources = Config.data.project.sources || [];
    this._render("ready", "可以运行 Verilator", [
      { state: sources.length ? "success" : "failed", text: `源文件：${sources.length} 个` },
      { state: "pending", text: "Lint/仿真/覆盖率失败时会显示结构化诊断" },
    ]);
    ToolStepUI.setTechnical("verilator", { meta: "等待运行 Verilator", command: command.text, log: this._logEl.textContent });
  },

  async _browseTb() {
    const result = await window.vflux.openFileDialog({ title: "选择 C++ Testbench", filters: [{ name: "C++ Files", extensions: ["cpp", "cc", "cxx"] }, { name: "All Files", extensions: ["*"] }] });
    if (result?.filePaths?.[0]) document.getElementById("verilator-tb").value = result.filePaths[0];
  },

  async _generateTb() {
    const top = Config.data.project.top_module || "top";
    const path = `${Config.getProjectDir()}/tb/tb_${top}.cpp`;
    const content = `// Auto-generated by Vflux\n#include \"V${top}.h\"\n#include \"verilated.h\"\n\nint main(int argc, char** argv) {\n  Verilated::commandArgs(argc, argv);\n  V${top} top;\n  for (int i = 0; i < 10; ++i) top.eval();\n  return 0;\n}\n`;
    await window.vflux.writeText(path, content);
    document.getElementById("verilator-tb").value = path;
    App.setStatus("已生成 Verilator Testbench 模板");
  },

  async run() {
    if (this._running) return;
    const sources = Config.data.project.sources || [];
    if (!sources.length) {
      this._render("failed", "还不能运行 Verilator", [{ state: "failed", text: "请先添加 HDL 源文件" }]);
      return;
    }
    this._running = true;
    this._logEl.textContent = "";
    Pipeline.set("verilator", "running");
    App.setStatus("Verilator 运行中...");
    this._render("running", "正在运行 Verilator", [
      { state: "running", text: "读取源文件" },
      { state: "running", text: "执行所选模式" },
    ]);
    const command = this._buildCommand();
    ToolStepUI.setTechnical("verilator", { meta: "运行中", command: command.text, log: "" });
    const result = await App.runTool("verilator", "verilator.exe", command.args, Config.getProjectDir(), (t) => this._appendLog(t));
    this._running = false;
    ToolStepUI.setTechnical("verilator", { meta: `退出码：${result.code ?? 0}`, command: command.text, log: this._logEl.textContent });
    Pipeline.set("verilator", result.success ? "success" : "failed", result.success ? "" : `code:${result.code}`);
    this._render(result.success ? "success" : "failed", result.success ? "Verilator 完成" : "Verilator 失败", result.success ? [
      { state: "success", text: "Verilator 已完成当前任务" },
    ] : ToolDiagnostics.analyze("verilator", this._logEl.textContent));
    App.setStatus(result.success ? "Verilator 完成" : "Verilator 失败");
    if (PanelDashboard) PanelDashboard.refresh();
  },

  cancel() {
    if (!this._running) return;
    App.cancelTool("verilator");
    this._running = false;
    Pipeline.set("verilator", "failed", "已取消");
    this._render("failed", "Verilator 已取消", [{ state: "failed", text: "任务被中断" }]);
  },

  _buildCommand() {
    const mode = document.getElementById("verilator-mode").value;
    const sources = Config.data.project.sources || [];
    const tb = document.getElementById("verilator-tb").value.trim();
    const buildMode = mode !== "lint" && !!tb;
    const args = mode === "lint" ? ["--lint-only"] : buildMode ? ["--cc", "--exe", "--build"] : ["--cc"];
    const sim = this._simulationArgs();
    args.push(...sim.compile);
    if (this._checked("verilator-opt-wall")) args.push("-Wall");
    if (this._checked("verilator-opt-trace") || mode === "trace") args.push(sim.traceFst ? "--trace-fst" : "--trace");
    if (this._checked("verilator-opt-coverage") || mode === "coverage") args.push("--coverage");
    if (buildMode && sim.cflags) args.push("-CFLAGS", sim.cflags);
    if (buildMode && sim.ldflags) args.push("-LDFLAGS", sim.ldflags);
    args.push(...sources);
    if (tb && mode !== "lint") args.push(tb);
    return { args, text: `verilator ${args.join(" ")}` };
  },

  _simulationArgs() {
    const flow = Config.getFlow("simulation");
    const enabled = Config.getFlow("verilator").use_sim_config !== false;
    if (!enabled) return { compile: [], cflags: "", ldflags: "", traceFst: false };
    const split = (value) => String(value || "").split(/[;,]/).map((item) => item.trim()).filter(Boolean);
    const compile = [
      ...split(flow.includes).map((dir) => `-I${dir}`),
      ...split(flow.defines).map((item) => `-D${item}`),
    ];
    if (flow.timescale) compile.push("--timescale", flow.timescale);
    return { compile, cflags: flow.cflags || "", ldflags: flow.ldflags || "", traceFst: !!flow.trace_fst };
  },

  _checked(id) { return !!document.getElementById(id)?.checked; },
  _appendLog(text) { ToolStepUI.appendHiddenLog(this._logEl, text); },
  _render(kind, summary, items) { ToolStepUI.render("verilator-result", "verilator-summary", "verilator-feedback-list", kind, summary, items); },
  _saveOptions() {
    Config.setFlowValue("verilator", "wall", this._checked("verilator-opt-wall"));
    Config.setFlowValue("verilator", "trace", this._checked("verilator-opt-trace"));
    Config.setFlowValue("verilator", "coverage", this._checked("verilator-opt-coverage"));
    this.refresh();
  },
  _loadOptions() {
    const flow = Config.getFlow("verilator");
    document.getElementById("verilator-opt-wall").checked = flow.wall !== false;
    document.getElementById("verilator-opt-trace").checked = !!flow.trace;
    document.getElementById("verilator-opt-coverage").checked = !!flow.coverage;
  },
};
